//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPage_F4.DangKi {
    
    
    public partial class DangKiTaiKhoanNguoiTimViec {
        
        /// <summary>
        /// uc_ThongBao1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebPage_F4.UserControl.uc_ThongBao uc_ThongBao1;
        
        /// <summary>
        /// uc_FormDangKiNguoiTimViec1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebPage_F4.UserControl.uc_Register_Nguoi_Tim_Viec uc_FormDangKiNguoiTimViec1;
    }
}
